USE DATABASE {{ env }}_VENDORS;
USE SCHEMA  REFINED;

CREATE TASK {{ env }}_VENDORS_RAW_TO_REFINED_TASK
  SCHEDULE = 'USING CRON 0 9-17 * * SUN America/Los_Angeles'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  AS CALL {{ env }}_VENDORS_RAW_TO_REFINED_INGESTION();