/*
USE DATABASE {{ env }}_VENDORS;
USE SCHEMA RAW;
ALTER STAGE {{ env }}_VENDORS_STAGE SET DIRECTORY = (ENABLE = TRUE);
COPY INTO {{ env }}_VENDORS_RAW_FIRST FROM @{{ env }}_VENDORS_STAGE FILES = ('VENDOR_RAW.csv');
COPY INTO {{ env }}_VENDORS_RAW_SECOND FROM @{{ env }}_VENDORS_STAGE FILES = ('VENDOR_RAW2.csv');
*/
USE DATABASE VENDORS;
USE SCHEMA RAW;
CREATE OR REPLACE STAGE {{ env }}_VENDORS_STAGE FILE_FORMAT = {{ env }}_VENDORS_FILE_FORMAT;
