USE DATABASE {{ env }}_VENDORS;
CREATE SCHEMA IF NOT EXISTS REFINED;
--ALTER TABLE raw_first ADD COLUMN PHONE VARCHAR;
CREATE TABLE IF NOT EXISTS refined_first
(
   FULL_NAME VARCHAR,PHONE VARCHAR
);
