/*
USE DATABASE  PEOPLESOFT;
USE SCHEMA RAW;
ALTER STAGE PEOPLESOFT_STAGE SET DIRECTORY = (ENABLE = TRUE);
COPY INTO XYZ FROM @PEOPLESOFT_STAGE FILE_FORMAT = (FORMAT_NAME = PEOPLESOFT_FILE_FORMAT);
COPY INTO PQR FROM @PEOPLESOFT_STAGE FILE_FORMAT = (FORMAT_NAME = PEOPLESOFT_FILE_FORMAT);
*/
USE DATABASE {{ env }}_PEOPLESOFT;
USE SCHEMA RAW;
CREATE OR REPLACE STAGE {{ env }}_PEOPLESOFT_STAGE FILE_FORMAT = {{ env }}_PEOPLESOFT_FILE_FORMAT;
