USE DATABASE {{ env }}_VENDORS;
USE SCHEMA CONSUMPTION;
CREATE OR REPLACE VIEW consumption_secondview AS SELECT CONCAT(FIRST_NAME,'--',LAST_NAME) AS FULL_NAME FROM {{ env }}_VENDORS.REFINED.refined_secondview;
