USE DATABASE {{ env }}_VENDORS;
CREATE SCHEMA IF NOT EXISTS CONSUMPTION;
CREATE OR REPLACE VIEW consumption_firstview AS SELECT CONCAT(FIRST_NAME,'--',LAST_NAME) AS FULL_NAME FROM {{ env }}_VENDORS.REFINED.refined_firstview;
