/*
CREATE TASK {{ env }}_VENDORS_RAW_TO_REFINED_TASK
  SCHEDULE = 'USING CRON 0 9-17 * * SUN America/Los_Angeles'
  USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
  AS CALL {{ env }}_VENDORS_RAW_TO_REFINED_INGESTION();
*/

create or  replace task REFINED.{{ env }}_DUMMY_TASK
warehouse={{ VAR_ENV_UC }}_ENGINEER_WH
as 
BEGIN
CALL DUMMY_PROCEDURE('DB_POC_VENDORS_{{ VAR_ENV_UC }}','REFINED','{{ VAR_ENV_UC }}');
END;