/*
USE DATABASE  VENDORS;
USE SCHEMA RAW;
CREATE STAGE IF NOT EXISTS VENDORS_STAGE FILE_FORMAT = VENDORS_FILE_FORMAT;
COPY INTO XYZ FROM @VENDORS_STAGE FILE_FORMAT = (FORMAT_NAME = VENDORS_FILE_FORMAT);
COPY INTO PQR FROM @VENDORS_STAGE FILE_FORMAT = (FORMAT_NAME = VENDORS_FILE_FORMAT);
*/
USE DATABASE VENDORS;
USE SCHEMA RAW;
ALTER STAGE VENDORS_STAGE SET DIRECTORY = (ENABLE = TRUE);